package com.pumpkin.core.input

object KeyCode {
    const val SPACE             =32
    const val APOSTROPHE        =39  /* ' */
    const val COMMA             =44  /* , */
    const val MINUS             =45  /* - */
    const val PERIOD            =46  /* . */
    const val SLASH             =47  /* / */
    const val _0                =48
    const val _1                =49
    const val _2                =50
    const val _3                =51
    const val _4                =52
    const val _5                =53
    const val _6                =54
    const val _7                =55
    const val _8                =56
    const val _9                =57
    const val SEMICOLON         =59  /* ; */
    const val EQUAL             =61  /* = */
    const val A                 =65
    const val B                 =66
    const val C                 =67
    const val D                 =68
    const val E                 =69
    const val F                 =70
    const val G                 =71
    const val H                 =72
    const val I                 =73
    const val J                 =74
    const val K                 =75
    const val L                 =76
    const val M                 =77
    const val N                 =78
    const val O                 =79
    const val P                 =80
    const val Q                 =81
    const val R                 =82
    const val S                 =83
    const val T                 =84
    const val U                 =85
    const val V                 =86
    const val W                 =87
    const val X                 =88
    const val Y                 =89
    const val Z                 =90
    const val LEFT_BRACKET      =91  /* [ */
    const val BACKSLASH         =92  /* \ */
    const val RIGHT_BRACKET     =93  /* ] */
    const val GRAVE_ACCENT      =96  /* ` */
    const val WORLD_1           =161 /* non-US #1 */
    const val WORLD_2           =162 /* non-US #2 */

/* Function  */
    const val ESCAPE             =256
    const val ENTER              =257
    const val TAB                =258
    const val BACKSPACE          =259
    const val INSERT             =260
    const val DELETE             =261
    const val RIGHT              =262
    const val LEFT               =263
    const val DOWN               =264
    const val UP                 =265
    const val PAGE_UP            =266
    const val PAGE_DOWN          =267
    const val HOME               =268
    const val END                =269
    const val CAPS_LOCK          =280
    const val SCROLL_LOCK        =281
    const val NUM_LOCK           =282
    const val PRINT_SCREEN       =283
    const val PAUSE              =284
    const val F1                 =290
    const val F2                 =291
    const val F3                 =292
    const val F4                 =293
    const val F5                 =294
    const val F6                 =295
    const val F7                 =296
    const val F8                 =297
    const val F9                 =298
    const val F10                =299
    const val F11                =300
    const val F12                =301
    const val F13                =302
    const val F14                =303
    const val F15                =304
    const val F16                =305
    const val F17                =306
    const val F18                =307
    const val F19                =308
    const val F20                =309
    const val F21                =310
    const val F22                =311
    const val F23                =312
    const val F24                =313
    const val F25                =314
    const val KP_0               =320
    const val KP_1               =321
    const val KP_2               =322
    const val KP_3               =323
    const val KP_4               =324
    const val KP_5               =325
    const val KP_6               =326
    const val KP_7               =327
    const val KP_8               =328
    const val KP_9               =329
    const val KP_DECIMAL         =330
    const val KP_DIVIDE          =331
    const val KP_MULTIPLY        =332
    const val KP_SUBTRACT        =333
    const val KP_ADD             =334
    const val KP_ENTER           =335
    const val KP_EQUAL           =336
    const val LEFT_SHIFT         =340
    const val LEFT_CONTROL       =341
    const val LEFT_ALT           =342
    const val LEFT_SUPER         =343
    const val RIGHT_SHIFT        =344
    const val RIGHT_CONTROL      =345
    const val RIGHT_ALT          =346
    const val RIGHT_SUPER        =347
    const val MENU               =348
}